function plot_classifier_comparison_accuracy()
	
    %% Preset Files 
	
	result_path = 'projects/+e_energy/results/classification/';
	figure_path = 'projects/+e_energy/images/';

    labels = { ...
		'Singles'...
		'OldHouses'...
        'Families'...
        'NoKids'...
        'Persons'...
		'eCooking'...
        'Retired'...
        'Employment'...
		'Floorarea'...
		'Devices'...
		'SocialClass'...
        'Bedrooms'...
		};
    
    labelsInPlot = { ...
        'single'...
        'age_house'...
        'family'...
        '#children'...
        '#residents'...
        'cooking'...
        'retirement'...
        'employment'...
        'floor_area'...
        '#devices'...
        'social_class'...
        '#bedrooms'...
    };
        
    method = { ...
            'knn'...
            'lda'...
            'mahal'...
            'svm'...
            };

    colors = { ...
            'r'...
            'b'...
            'g'...
            'k'...
            };
        %[1,0.4,0.6]...
        
    markers = { ...
            '*'...
            '+'...
            'x'...
            };

    l_legend = {'kNN', ...
                'LDA', ...
                'Mahal.', ...
                'SVM' ...
               };

    width = 12; 
    height = 7.5;
    
    num_methods = length(method);
    num_labels = length(labels);
    fm_all = zeros(num_methods, num_labels);
    for l = 1:num_labels
        for m = 1:length(method)
			load([result_path, 'sCR-', labels{l}, '_all_', method{m}, '.mat']);
            fm_all(m,l) = accuracy(sCR);
        end
    end

    %% Plot results
	fig_h = figure();
	hold on;
    
    for l=1:num_labels
        for m=1:3
            tmp = plot(l, fm_all(m,l), markers{m}, 'Color', colors{m});
            set(tmp, 'MarkerFaceColor', colors{m});
        end
        
        plot_x = l;
        plot_y = fm_all(4,l);
        plot([plot_x-0.2 plot_x+0.2], [plot_y plot_y],'-', 'Color', colors{4});
    end
    
    hold off;
    
    xlim([0, (length(labels)+1)]);

    ylim([0.2 0.9]);
    ylabel('Accuracy');
    set(gca, 'YGrid', 'on');
    set(gca, 'XGrid', 'on');
    
    legend(l_legend, 'Location', 'NorthOutside', 'orientation', 'horizontal');
    %legend(l_legend, 'Location', 'NE');
    
    fig_h = make_report_ready(fig_h, 'size', [width height], 'fontsize', 9);
	    
    y_ticks = [ 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 ];
    set(gca, 'YTick', y_ticks);
    y_tick_labels = cell(1, length(y_ticks));
    xticklabel_rotate(1:length(labelsInPlot),45,labelsInPlot,'interpreter','none');
    for i = 1:length(y_ticks)
       y_tick_labels{i} = [num2str(y_ticks(i)*100), '%'];
    end
    set(gca, 'YTickLabel', y_tick_labels);
   
    %% Save figure
	filename = 'classifier_comparison_accuracy';
    warning off
    mkdir(figure_path);
    warning on
    saveas(fig_h, [figure_path, filename, '.eps'], 'psc2');
  	close(fig_h);
end


