% This file is part of the project CLASS (https://github.com/beckel/class).
% Licence: GPL 2.0 (http://www.gnu.org/licenses/gpl-2.0.html)
% Copyright: ETH Zurich & TU Darmstadt, 2012
% Authors: Christian Beckel (beckel@inf.ethz.ch), Leyna Sadamori (sadamori@inf.ethz.ch)

function sClass = class_lightbulb_ratio(option)
	if (nargin == 0)
		sClass.classes = { ...
			'High', ...
			'Low', ...
			}; 
		sClass.constr = { ...
			{ '<= 0.5' }, ...
			{ '> 0.5' }, ...
			};
        sClass.constraint_names = { ...
            'ratio_energy_saving_lamps', ...
        };
    elseif (nargin == 1)
		if (strcmp(option, 'name'))
			sClass = 'LightBulbRatio';
		else
			error('This option is not supported');
		end
	end
end