% This file is part of the project CLASS (https://github.com/beckel/class).
% Licence: GPL 2.0 (http://www.gnu.org/licenses/gpl-2.0.html)
% Copyright: ETH Zurich & TU Darmstadt, 2012
% Authors: Christian Beckel (beckel@inf.ethz.ch), Leyna Sadamori (sadamori@inf.ethz.ch)

function sClass = class_absence(option)
	if (nargin == 0)
		sClass.classes = { ...
			'Absent', ...
			'Present', ...
			}; 
		sClass.constr = { ...
			{ '> 5' }, ...
			{ '<= 5' }, ...
			};
        sClass.constraint_names = { ...
            'hours_at_home', ...
        };
    elseif (nargin == 1)
		if (strcmp(option, 'name'))
			sClass = 'Absence';
		else
			error('This option is not supported');
		end
	end
end