function sClass = class_ecooking(option)
	if (nargin == 0)
		sClass.classes = { ...
			'e-Cooking', ...
			'Other', ...
			};
		sClass.constr = { ...
			'Cooking = 1', ...
			'Cooking = 2', ...
			};
	elseif (nargin == 1)
		if (strcmp(option, 'name'))
			sClass = 'eCooking';
		else
			error('This option is not supported');
		end
	end
end