function sClass = class_old_house(option)
	if (nargin == 0)
		sClass.classes = { ...
			'OldHouses', ...
			'Other', ...
			};
		sClass.constr = { ...
			'House_Age > 2', ...
			'House_Age <= 2', ...
			};
	elseif (nargin == 1)
		if (strcmp(option, 'name'))
			sClass = 'OldHouses';
		else
			error('This option is not supported');
		end
	end
end