function sClass = class_dink(option)
	if (nargin == 0)
		sClass.classes = { ...
			'DINK', ...
			'Other', ...
			};
		sClass.constr = { ...
			'Adults = 2 AND Children = 0', ...
			'Adults != 2 OR Children > 0', ...
			};
	elseif (nargin == 1)
		if (strcmp(option, 'name'))
			sClass = 'DINK';
		else
			error('This option is not supported');
		end
	end
end