function sClass = class_eheating(option)
	if (nargin == 0)
		sClass.classes = { ...
			'e-Heating', ...
			'Other', ...
			};
		sClass.constr = { ...
			'(Heat_Type BETWEEN 1 AND 2) OR (Water_Type BETWEEN 2 AND 3)', ...
			'NOT((Heat_Type BETWEEN 1 AND 2) OR (Water_Type BETWEEN 2 AND 3))', ...
			};
	elseif (nargin == 1)
		if (strcmp(option, 'name'))
			sClass = 'eHeating';
		else
			error('This option is not supported');
		end
	end
end