function sClass = class_devices(option)
	if (nargin == 0)
		sClass.classes = { ...
			'Low', ...
			'Mid', ...
			'High', ...
			};
		sClass.constr = { ...
			'(Appliances + Entertainment <= 8)', ...
			'((Appliances + Entertainment > 8) AND (Appliances + Entertainment <= 11))', ...
			'(Appliances + Entertainment > 11)', ...
			};
	elseif (nargin == 1)
		if (strcmp(option, 'name'))
			sClass = 'Devices';
		else
			error('This option is not supported');
		end
	end
end