% This file is part of the project CLASS (https://github.com/beckel/class).
% Licence: GPL 2.0 (http://www.gnu.org/licenses/gpl-2.0.html)
% Copyright: ETH Zurich & TU Darmstadt, 2012
% Authors: Christian Beckel (beckel@inf.ethz.ch), Leyna Sadamori (sadamori@inf.ethz.ch)

function sClass = class_socialclass(option)
	if (nargin == 0)
		sClass.classes = { ...
			'AB', ...
			'C', ...
			'DE', ...
			};
		sClass.constr = { ...
			'Social_Class = 1', ...
			'Social_Class BETWEEN 2 AND 3', ...
			'Social_Class = 4', ...
			};
	elseif (nargin == 1)
		if (strcmp(option, 'name'))
			sClass = 'SocialClass';
		else
			error('This option is not supported');
		end
	end
end