function sClass = class_appliances(option)
	if (nargin == 0)
		sClass.classes = { ...
			'Low', ...
			'Mid', ...
			'High', ...
			}; 
		sClass.constr = { ...
			'(Appliances < 5)', ...
			'(Appliances <= 7 AND Appliances >= 5)', ...
			'(Appliances > 7)', ...
			};
	elseif (nargin == 1)
		if (strcmp(option, 'name'))
			sClass = 'Appliances';
		else
			error('This option is not supported');
		end
	end
end