function sClass = class_floorarea(option)
	if (nargin == 0)
		sClass.classes = { ...
			'Small', ...
			'Middle', ...
			'Big', ...
			};
		sClass.constr = { ...
			'Floorsize < 100', ...
			'Floorsize BETWEEN 100 AND 200', ...
			'Floorsize > 200', ...
			};
	elseif (nargin == 1)
		if (strcmp(option, 'name'))
			sClass = 'Floorarea';
		else
			error('This option is not supported');
		end
	end
end