function sClass = class_nokids(option)
	if (nargin == 0)
		sClass.classes = { ...
			'NoKids', ...
			'Other', ...
			};
		sClass.constr = { ...
			'Children = 0', ...
			'Children > 0', ...
			};
	elseif (nargin == 1)
		if (strcmp(option, 'name'))
			sClass = 'NoKids';
		else
			error('This option is not supported');
		end
	end
end