% This file is part of the project CLASS (https://github.com/beckel/class).
% Licence: GPL 2.0 (http://www.gnu.org/licenses/gpl-2.0.html)
% Copyright: ETH Zurich & TU Darmstadt, 2012
% Authors: Christian Beckel (beckel@inf.ethz.ch), Leyna Sadamori (sadamori@inf.ethz.ch)

function sClass = class_devices_complex(option)
	if (nargin == 0)
		sClass.classes = { ...
			'Low', ...
			'Mid', ...
			'High', ...
			};
		sClass.constr = { ...
			'(Appliances < 5 AND Entertainment < 5)', ...
			'(((Appliances BETWEEN 5 AND 7) AND Entertainment <= 8) OR ((Entertainment BETWEEN 5 AND 8) AND Appliances <= 7))', ...
			'(Appliances > 7 OR Entertainment > 8)', ...
			};
	elseif (nargin == 1)
		if (strcmp(option, 'name'))
			sClass = 'DevicesComplex';
		else
			error('This option is not supported');
		end
	end
end