function sClass = class_employment(option)
	if (nargin == 0)
		sClass.classes = { ...
			'Employed', ...
			'Other', ...
			};
		sClass.constr = { ...
			'Employment = 1', ...
			'Employment != 1', ...
			};
	elseif (nargin == 1)
		if (strcmp(option, 'name'))
			sClass = 'Employment';
		else
			error('This option is not supported');
		end
	end
end