function sClass = class_bedrooms(option)
	if (nargin == 0)
		sClass.classes = { ...
			'1-2', ...
			'3', ...
			'4', ...
			'5+', ...
			};
		sClass.constr = { ...
			'Bedrooms BETWEEN 1 AND 2', ...
			'Bedrooms = 3', ...
			'Bedrooms = 4', ...
			'Bedrooms = 5', ...
			};
	elseif (nargin == 1)
		if (strcmp(option, 'name'))
			sClass = 'Bedrooms';
		else
			error('This option is not supported');
		end
	end
end