function sClass = class_retired(option)
	if (nargin == 0)
		sClass.classes = { ...
			'Retired', ...
			'Other', ...
			};
		sClass.constr = { ...
			'Employment = 3', ...
			'Employment != 3', ...
			};
	elseif (nargin == 1)
		if (strcmp(option, 'name'))
			sClass = 'Retired';
		else
			error('This option is not supported');
		end
	end
end