function sClass = class_families(option)
	if (nargin == 0)
		sClass.classes = { ...
			'Family', ...
			'Other', ...
			};
		sClass.constr = { ...
			'Adults > 1 AND Children > 0', ...
			'Adults < 2 OR Children = 0', ...
			};
	elseif (nargin == 1)
		if (strcmp(option, 'name'))
			sClass = 'Families';
		else
			error('This option is not supported');
		end
	end
end