function sClass = apriori_singles(option)
	if (nargin == 0)
		sClass.classes = { ...
			'Singles', ...
			'Other', ...
			};
		sClass.constr = { ...
			'Adults = 1 AND Children = 0', ...
			'Persons > 1', ...
			};
	elseif (nargin == 1)
		if (strcmp(option, 'name'))
			sClass = 'Singles';
		else
			error('This option is not supported');
		end
	end
end