function sClass = apriori_bedrooms(option)
	if (nargin == 0)
		sClass.classes = { ...
			'1-3', ...
			'3+', ...
			};
		sClass.constr = { ...
			'Bedrooms BETWEEN 1 AND 3', ...
			'Bedrooms > 3', ...
			};
	elseif (nargin == 1)
		if (strcmp(option, 'name'))
			sClass = 'Bedrooms';
		else
			error('This option is not supported');
		end
	end
end