function sClass = apriori_floorarea(option)
	if (nargin == 0)
		sClass.classes = { ...
			'<180qm', ...
			'>180qm', ...
			};
		sClass.constr = { ...
			'Floorsize < 180', ...
			'Floorsize >= 180', ...
			};
	elseif (nargin == 1)
		if (strcmp(option, 'name'))
			sClass = 'Floorarea';
		else
			error('This option is not supported');
		end
	end
end