function sClass = apriori_typehouse(option)
	if (nargin == 0)
		sClass.classes = { ...
			'Semi-Detatched', ...
			'Detatched', ...
			'Terraced', ...
			'Bungalow', ...
			};
		sClass.constr = { ...
			'House_Type = 2', ...
			'House_Type = 3', ...
			'House_Type = 4', ...
			'House_Type = 5', ...
			};
% 		sClass.classes = { ...
% 			'Apartment', ...
% 			'Semi-Detatched', ...
% 			'Detatched', ...
% 			'Terraced', ...
% 			'Bungalow', ...
% 			};
% 		sClass.constr = { ...
% 			'House_Type = 1', ...
% 			'House_Type = 2', ...
% 			'House_Type = 3', ...
% 			'House_Type = 4', ...
% 			'House_Type = 5', ...
% 			};
	elseif (nargin == 1)
		if (strcmp(option, 'name'))
			sClass = 'House_Type';
		else
			error('This option is not supported');
		end
	end
end