function sClass = apriori_persons(option)
	if (nargin == 0)
		sClass.classes = { ...
			'1-2', ...
			'3+', ...
			};
		sClass.constr = { ...
			'Persons BETWEEN 1 AND 2', ...
			'Persons > 2', ...
			};
	elseif (nargin == 1)
		if (strcmp(option, 'name'))
			sClass = 'Persons';
		else
			error('This option is not supported');
		end
	end
end