function sClass = apriori_age(option)
	if (nargin == 0)
		sClass.classes = { ...
			'<35', ...
			'35-65', ...
			'65+', ...
			};
		sClass.constr = { ...
			'Age BETWEEN 1 AND 2', ...
			'Age BETWEEN 3 AND 5', ...
			'Age = 6', ...
			};
	elseif (nargin == 1)
		if (strcmp(option, 'name'))
			sClass = 'Age';
		else
			error('This option is not supported');
		end
	end
end