function sClass = apriori_ownhouse(option)
	if (nargin == 0)
		sClass.classes = { ...
			'Rent', ...
			'Own', ...
			};
		sClass.constr = { ...
			'House_Ownership = 1', ...
			'House_Ownership = 2', ...
			};
	elseif (nargin == 1)
		if (strcmp(option, 'name'))
			sClass = 'House_Ownership';
		else
			error('This option is not supported');
		end
	end
end