% This file is part of the project CLASS (https://github.com/beckel/class).
% Licence: GPL 2.0 (http://www.gnu.org/licenses/gpl-2.0.html)
% Copyright: ETH Zurich & TU Darmstadt, 2012
% Authors: Christian Beckel (beckel@inf.ethz.ch), Leyna Sadamori (sadamori@inf.ethz.ch)

function sClass = class_entertainment_tg(option)
	if (nargin == 0)
		sClass.classes = { ...
			'0-1', ...
			'2', ...
            '>= 3', ...
			}; 
		sClass.constr = { ...
			'((PreTrial_Answers.Q95 + PreTrial_Answers.Q96 + PreTrial_Answers.Q99 - 3) <= 1)', ...
			'((PreTrial_Answers.Q95 + PreTrial_Answers.Q96 + PreTrial_Answers.Q99 - 3) = 2)', ...
			'((PreTrial_Answers.Q95 + PreTrial_Answers.Q96 + PreTrial_Answers.Q99 - 3) >= 3)', ...
			};
	elseif (nargin == 1)
		if (strcmp(option, 'name'))
			sClass = 'App_Entertainment_TG';
		else
			error('This option is not supported');
		end
	end
end
