function [ ret ] = get_combinations()

    ret = {
        {
        'Retired', 1; ...
        'Devices', 3; ...
        },...
        {
        'Employment', 1;...
        'HouseType', 1;...
        },...
        {
        'Employment', 1;...
        'Unoccupied', 1;...
        },...
        {
        'Employment', 1;...
        'Unoccupied', 1;...
        'Income', 2;...
        },...
        {
        'Floorarea', 3;...
        'OldHouses', 1;...
        },...
        {
        'Families', 1;...
        'Devices', 3;...
        'SocialClass', 1:2;...
        },...
        {
        'Employment', 1;...
        'Singles', 1;...
        'Age', 2;...
        },...
        {
        'All_Employed', 1;...
        'Floorarea', 3;...
        },...
        {
        'All_Employed', 1;...
        'Floorarea', 3;...
        'OldHouses', 1;...
        },...
        {
        'eCooking', 1;...
        'Persons', 2;...
        },...
        {
        'Age', 2;...
        'Persons', 2;...
        'Employment', 1;...
        'SocialClass', 1:2;...
        },...
        {
        'All_Employed', 1;...
        'Devices', 3; ...
        },...
        {
        'Income', 2;
        'Employment', 1;...
        'All_Employed', 1;...
        'SocialClass', 1:2;...
        },...
        {
        'Bedrooms', 3:4;...
        'Floorarea', 3;...
        'HouseType', 1;...
        },...
        {
        'Singles', 2;...
        'Persons', 2;...
        'Families', 1;...
        'Unoccupied', 2;...
        },...
        {
        'SocialClass', 3;...
        'Income', 1;...
        'Employment', 2;...
        'All_Employed', 2;...
        },...
    };

end

